/**
 * Open-time vault conformance check — DETECTION ONLY.
 *
 * WHAT THIS IS FOR. A router-managed vault carries a small set of generated
 * navigation files under `wiki/`: a root `index.md`, one `index.md` per
 * directory on the way to a content page, and a newest-first `log.md`. They are
 * projections of the tree, regenerated by the MCP router. Nothing runs when a
 * vault is merely OPENED in Obsidian, so a vault whose projections were never
 * built — or that drifted after folders were created by hand — looks perfectly
 * fine until something far away misbehaves.
 *
 * This module closes exactly that observation gap, and nothing more.
 *
 * WHAT IT MUST NEVER DO, and why the file is written this way.
 *
 *   1. IT NEVER GENERATES. There is exactly ONE implementation of the
 *      projection generator, and it lives in the router
 *      (`src/helpers/okf-projections.mjs`, shared with the OKF bundle
 *      exporter). Porting it here — into another language, another repo, on
 *      another release train — would create a second implementation that
 *      diverges the first time either side is fixed, and the two would write
 *      different bytes into the same files. So this module knows how to
 *      RECOGNISE a projection and how to notice one is missing. It has no
 *      content builder, and the whole module is free of writes: there is no
 *      `adapter.write` and no string that could become file content.
 *   2. IT NEVER WRITES ON OPEN. Opening a vault must not mutate it. The only
 *      outputs are a Notice and an in-memory report the settings tab renders.
 *   3. IT SAYS NOTHING ABOUT A VAULT IT DOES NOT MANAGE. See below — this is
 *      the single most important rule in the file.
 *
 * APPLICABILITY IS THE `wiki-meta/` SCAFFOLD, NOT THE PRESENCE OF `wiki/`.
 *
 * The first version keyed on "are there markdown files under `wiki/`". That is
 * wrong in the direction that produces false accusations: plenty of people have
 * a hand-made folder called `wiki` in a vault the router has never touched, and
 * telling them their vault is non-conformant — repeatedly, on every open — is
 * both untrue and rude. What actually identifies a router-managed vault is the
 * private scaffold the provisioner writes: `wiki-meta/catalog.md` (or
 * `wiki-meta/index.md` on a vault still carrying the pre-0.58.0 names). No
 * scaffold, no opinion. This is the same signal the router itself now uses to
 * decide whether to maintain a vault, which is what makes the Notice's promise
 * ("the router will repair this") true rather than aspirational.
 *
 * THE MARKER (and the scaffold names, and the index path) ARE COPIED CONSTANTS,
 * DELIBERATELY. `PROJECTION_MARKER`, `SCAFFOLD_CANDIDATES` and
 * `SEARCH_INDEX_PATH` below duplicate the router's values. They have to: the two
 * live in separate repositories that ship and auto-update independently, so
 * there is no import to share.
 *
 * WHAT THE TESTS ACTUALLY GUARANTEE — stated honestly, because the obvious
 * phrasing is a lie. `tests/conformance-core.test.mjs` pins each of these
 * constants to its expected literal *within this repository*. That catches an
 * accidental LOCAL edit (a typo, a careless rename) here. It does NOT — cannot —
 * detect a drift on the ROUTER side: the assertion compares a bridge constant to
 * a bridge literal and never observes the router at all. Measured: changing the
 * marker on the router alone leaves this suite fully green.
 *
 * And that gap is not fixable by a "better" test. A cross-repo pin (this suite
 * reading the router's `src/helpers/okf-projections.mjs`) would pass only on a
 * dev machine where both repos sit side by side, and would be absent-or-broken
 * in the bridge's own CI and in the shipped plugin bundle, which carry no router
 * source — a false-reliable check, worse than none. So there is no such pin, and
 * none should be added.
 *
 * The ONLY real protection against router-side drift is therefore: (1) the
 * router keeping these constants stable (the marker prefix is documented there
 * as STABLE — changing it orphans every deployed projection), and (2) this
 * comment naming the coupling so a router change prompts a matching edit here.
 * If the router ever does change one, the symptom here depends on WHICH
 * constant drifted. Scaffold-name drift is silent: a vault provisioned under
 * the new name stops looking managed to this check, and the Notice goes quiet
 * on a vault that is actually drifted. Marker drift fails the opposite way —
 * noisy in the wrong direction: every regenerated file fails
 * hasProjectionMarker(), lands in unmarked[], and the Notice accuses a healthy
 * vault of hand-written files.
 *
 * No `obsidian` import anywhere in this file, so `node --test` can drive every
 * branch — including "a Notice was produced" — with injected callbacks. Same
 * rationale as src/folder-hiding-core.mjs and src/handlers/open-params.mjs.
 */

/**
 * MUST match `PROJECTION_MARKER` in the router's src/helpers/okf-projections.mjs.
 * The test pins this to its literal value HERE (catching a local edit); it does
 * not and cannot observe the router — see the module header. Changing it here
 * without changing it there, OR on the router without changing it here, makes
 * every generated file fail the marker check: it lands in `unmarked[]` and the
 * Notice accuses a healthy vault (noisy drift, not silent — see the header).
 */
export const PROJECTION_MARKER = 'Generated by obsidian-mcp-router';

/** The wiki content root. Everything this check looks at lives under it. */
export const WIKI_ROOT = 'wiki';

/** The private scaffold directory the router provisioner writes. */
export const WIKI_META_ROOT = 'wiki-meta';

/**
 * The scaffold file whose presence means "the router manages this vault",
 * current name first. Mirrors the router's `scaffoldCandidates('catalog')`:
 * v0.58.0 renamed `wiki-meta/index.md` → `wiki-meta/catalog.md` because OKF
 * reserves the `index` basename, and vaults that never migrated still carry the
 * old one. The test pins these literals HERE (a local-edit guard) but cannot see
 * the router — see the module header on why no cross-repo pin exists.
 */
export const SCAFFOLD_CANDIDATES = [`${WIKI_META_ROOT}/catalog.md`, `${WIKI_META_ROOT}/index.md`];

/** Vault-relative path of the newest-first content log. */
export const LOG_PATH = `${WIKI_ROOT}/log.md`;

/** Vault-relative path of the root navigation index. */
export const ROOT_INDEX_PATH = `${WIKI_ROOT}/index.md`;

/** The router's local BM25 index. Presence is reported; nothing else is read. */
export const SEARCH_INDEX_PATH = `${WIKI_META_ROOT}/search-index.json`;

/** How many files the marker check reads at once. */
export const MARKER_READ_CONCURRENCY = 8;

/** Normalize a vault path the way Obsidian reports it: `/`-separated, no `./`. */
function normalize(p) {
  return String(p ?? '').replace(/\\/g, '/').replace(/^\.\//, '');
}

/**
 * Is this vault-relative path one of the RESERVED projection paths?
 *
 * Mirrors the router's `isProjectionPath`: exact lowercase basenames only, so a
 * user's `Index.md` stays their content. This rule is a hand-kept copy of the
 * router's — like the constants above, no test enforces cross-repo agreement
 * (none reliably can; see the module header), so keeping it in step is a manual
 * discipline, not a checked invariant.
 */
export function isProjectionPath(relPath) {
  const p = normalize(relPath);
  return p === LOG_PATH || new RegExp(`^${WIKI_ROOT}/(?:.+/)?index\\.md$`).test(p);
}

/** Is this a wiki CONTENT page — under `wiki/`, and not a generated file? */
export function isWikiContentPath(relPath) {
  const p = normalize(relPath);
  return new RegExp(`^${WIKI_ROOT}/.+\\.md$`, 'i').test(p) && !isProjectionPath(p);
}

/**
 * Does this vault carry the router's private scaffold?
 *
 * @param {string[]} paths every file path in the vault (markdown is enough —
 *   both scaffold candidates are `.md`).
 */
export function hasRouterScaffold(paths) {
  const present = new Set((Array.isArray(paths) ? paths : []).map(normalize));
  return SCAFFOLD_CANDIDATES.some((c) => present.has(c));
}

/**
 * Does this content carry the projection marker?
 *
 * Head-scan of the first 20 lines, matching the router's rule exactly: the
 * marker sits just after the optional frontmatter and heading, and scanning the
 * whole file would let a page that merely QUOTES the marker pass as generated.
 */
export function hasProjectionMarker(content) {
  if (typeof content !== 'string' || !content) return false;
  return content.split(/\r?\n/, 20).some((line) => line.startsWith(`> ${PROJECTION_MARKER}`));
}

/**
 * Which projection files SHOULD exist, given the content pages present.
 *
 * The rule is the router's, restated over paths (which is all detection needs):
 * the root index, `log.md`, and an `index.md` in every ANCESTOR directory of
 * every content page — intermediate directories included, even when they hold
 * no page of their own.
 *
 * A scaffolded vault with NO content still expects the root index and the log:
 * that is exactly what the provisioner writes into a newborn vault, so an empty
 * wiki is a legitimate, checkable state rather than an absence of one.
 *
 * @param {string[]} mdPaths every markdown path in the vault
 * @returns {string[]} sorted, deduped, vault-relative paths
 */
export function expectedProjectionPaths(mdPaths) {
  const contentPages = (Array.isArray(mdPaths) ? mdPaths : []).map(normalize).filter(isWikiContentPath);

  const expected = new Set([ROOT_INDEX_PATH, LOG_PATH]);
  for (const page of contentPages) {
    const segments = page.split('/'); // ['wiki', …dirs, 'page.md']
    // Every ancestor directory between `wiki/` and the page itself.
    for (let i = 1; i < segments.length - 1; i += 1) {
      expected.add(`${segments.slice(0, i + 1).join('/')}/index.md`);
    }
  }
  return [...expected].sort();
}

/**
 * Build the conformance report for one vault.
 *
 * @param {object} input
 * @param {string[]} input.mdPaths Every markdown path in the vault.
 * @param {Map<string,string|null>} [input.contents] Content of each PRESENT
 *   expected projection (path → text, or null when it could not be read).
 * @param {boolean} [input.searchIndexPresent] Does `wiki-meta/search-index.json`
 *   exist? PRESENCE ONLY — never its version, never its freshness.
 * @returns {{
 *   status: 'not-managed'|'conformant'|'incomplete',
 *   missing: string[], unmarked: string[], unreadable: string[],
 *   contentPages: number, expected: number, searchIndexPresent: boolean
 * }}
 */
export function conformanceReport({ mdPaths, contents = new Map(), searchIndexPresent = false }) {
  const paths = (Array.isArray(mdPaths) ? mdPaths : []).map(normalize);

  // APPLICABILITY FIRST, and on the scaffold — never on the presence of `wiki/`.
  // A hand-made `wiki` folder in somebody's personal vault is not a router vault
  // and must never be told it is broken.
  if (!hasRouterScaffold(paths)) {
    return {
      status: 'not-managed',
      missing: [],
      unmarked: [],
      unreadable: [],
      contentPages: 0,
      expected: 0,
      searchIndexPresent: false,
    };
  }

  const present = new Set(paths);
  const contentPages = paths.filter(isWikiContentPath);
  const expected = expectedProjectionPaths(paths);
  const missing = expected.filter((p) => !present.has(p));

  // EVERY expected projection is checked for the marker, not just the two at the
  // root. An unmarked `wiki/a/index.md` is a hand-written file the router
  // classifies as a CONFLICT and refuses to overwrite — reporting the vault as
  // conformant while the router reports a conflict is the two halves of this
  // feature disagreeing about the same file.
  const unmarked = [];
  const unreadable = [];
  for (const p of expected) {
    if (!present.has(p)) continue;
    const content = contents.get(p);
    if (content === null || content === undefined) {
      // Could not read it. NOT "conformant" — we did not verify anything.
      unreadable.push(p);
      continue;
    }
    if (!hasProjectionMarker(content)) unmarked.push(p);
  }

  return {
    status: missing.length === 0 && unmarked.length === 0 && unreadable.length === 0
      ? 'conformant'
      : 'incomplete',
    missing,
    unmarked,
    unreadable,
    contentPages: contentPages.length,
    expected: expected.length,
    searchIndexPresent: Boolean(searchIndexPresent),
  };
}

/** Cap on how many paths a Notice enumerates before it says "and N more". */
const NOTICE_PATH_CAP = 3;

function summarizePaths(paths) {
  if (paths.length <= NOTICE_PATH_CAP) return paths.join(', ');
  return `${paths.slice(0, NOTICE_PATH_CAP).join(', ')} (+${paths.length - NOTICE_PATH_CAP})`;
}

/**
 * The Notice text for a report, or `null` when nothing should be said.
 *
 * `null` is the answer for every silent case — conformant, not managed, and the
 * check having failed outright — so a caller cannot accidentally turn one of
 * them into a message.
 *
 * The text names the router as the thing that repairs, because this plugin does
 * not and will not.
 *
 * @param {object|null} report
 * @returns {string|null}
 */
export function noticeForReport(report) {
  if (!report || report.status !== 'incomplete') return null;

  const parts = [];
  if (report.missing.length > 0) {
    parts.push(`${report.missing.length} manquant(s) : ${summarizePaths(report.missing)}`);
  }
  if (report.unmarked.length > 0) {
    parts.push(`non marqué(s) : ${summarizePaths(report.unmarked)}`);
  }
  if (report.unreadable?.length > 0) {
    parts.push(`illisible(s) : ${summarizePaths(report.unreadable)}`);
  }
  return (
    `MCP Router Bridge — index de navigation incomplets dans wiki/ · ${parts.join(' — ')}. ` +
    'Ce plugin ne génère rien : lancez `refresh_okf_projections` côté routeur ' +
    '(ou ouvrez une session Claude sur ce vault, qui répare au premier contact). · ' +
    'Navigation indexes are incomplete; the MCP router regenerates them.'
  );
}

/**
 * One-line status for the settings tab. Always returns a string — the settings
 * tab has room to say "conformant", "not managed" and "the check itself failed",
 * where a Notice does not.
 *
 * @param {object|null} report `null` = never run; `{failed: true}` = the check
 *   threw (an unreadable vault is not a conformant one).
 * @param {boolean} enabled
 */
export function statusLineForReport(report, enabled) {
  if (!enabled) return 'Check disabled — turn the switch on to see this vault’s status.';
  if (!report) return 'Not checked yet (runs once when the vault finishes loading).';
  if (report.failed) {
    return `Check FAILED — ${report.error || 'the vault could not be read'}. This is not a verdict on the vault; press “Re-check”.`;
  }
  if (report.status === 'not-managed') {
    return 'Not a router-managed vault (no wiki-meta scaffold) — nothing to check, and nothing will be reported.';
  }

  const index = report.searchIndexPresent
    ? `Local search index present (${SEARCH_INDEX_PATH}).`
    : `No local search index yet (${SEARCH_INDEX_PATH}) — the router builds it on its first contact with this vault.`;

  if (report.status === 'conformant') {
    return `Conformant — ${report.expected} navigation file(s) present for ${report.contentPages} page(s). ${index}`;
  }
  const bits = [];
  if (report.missing.length > 0) bits.push(`${report.missing.length} missing: ${report.missing.join(', ')}`);
  if (report.unmarked.length > 0) bits.push(`${report.unmarked.length} unmarked: ${report.unmarked.join(', ')}`);
  if (report.unreadable?.length > 0) bits.push(`${report.unreadable.length} unreadable: ${report.unreadable.join(', ')}`);
  return `Incomplete — ${bits.join(' · ')}. The MCP router regenerates these; this plugin never writes them. ${index}`;
}

/**
 * Read up to `limit` files at a time. Bounded because a large vault can expect
 * dozens of directory indexes and firing them all at once on the UI thread's
 * event loop is how a "cheap check" becomes a visible hitch on vault open.
 */
async function readAllBounded(paths, readFile, limit = MARKER_READ_CONCURRENCY) {
  const out = new Map();
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, paths.length) }, async () => {
    for (;;) {
      const i = cursor;
      cursor += 1;
      if (i >= paths.length) return;
      const p = paths[i];
      try {
        out.set(p, await readFile(p));
      } catch {
        out.set(p, null); // unreadable → reported, never silently "conformant"
      }
    }
  });
  await Promise.all(workers);
  return out;
}

/**
 * Run the open-time check.
 *
 * Every effect is injected, which is what makes the branches — Notice,
 * silence-because-conformant, silence-because-off, silence-because-not-managed,
 * and the check itself failing — observable from a plain node test with no
 * Obsidian around.
 *
 * @param {object} input
 * @param {boolean} input.enabled The per-vault setting. OFF means OFF: no
 *   listing, no read, no Notice, and `null` back.
 * @param {() => (string[]|Promise<string[]>)} input.listMarkdownPaths
 * @param {(path: string) => Promise<string|null>} input.readFile Returns null
 *   when the file cannot be read (absent, locked).
 * @param {(path: string) => Promise<boolean>} [input.fileExists] Presence probe
 *   for non-markdown paths (the search index). Absent → reported as not present.
 * @param {(message: string) => void} input.notify
 * @returns {Promise<object|null>} the report, or null when the check did not run.
 */
export async function runOpenCheck({ enabled, listMarkdownPaths, readFile, fileExists, notify }) {
  if (!enabled) return null;

  const mdPaths = (await listMarkdownPaths()) || [];

  // Cheapest question first: is this even a router vault? A vault without the
  // scaffold costs one Set lookup and zero reads.
  if (!hasRouterScaffold(mdPaths)) {
    return conformanceReport({ mdPaths });
  }

  const present = new Set(mdPaths.map(normalize));
  const toRead = expectedProjectionPaths(mdPaths).filter((p) => present.has(p));
  const contents = await readAllBounded(toRead, readFile);

  let searchIndexPresent = false;
  if (typeof fileExists === 'function') {
    try {
      searchIndexPresent = Boolean(await fileExists(SEARCH_INDEX_PATH));
    } catch {
      searchIndexPresent = false;
    }
  }

  const report = conformanceReport({ mdPaths, contents, searchIndexPresent });
  const message = noticeForReport(report);
  if (message && typeof notify === 'function') notify(message);
  return report;
}
